In [1]:
import torch

In [2]:
# 1-d tensor
a= torch.tensor([2,2,1])
print(a)
# size
print(a.shape)
print(a.size())

tensor([2, 2, 1])
torch.Size([3])
torch.Size([3])


In [3]:
# 2-d tensor
b = torch.tensor([[2,1,4],[3,5,4],[1,2,0],[4,3,2]])
# get no.of rows/height of b
print(b.shape[0])

4


In [4]:
c= torch.FloatTensor([[2,1,4],[3,5,4],[1,2,0],[4,3,2]])
print(c)
# For double tensor you can give as
d= torch.tensor([2,2,1], dtype=torch.float)
print(d.mean())

tensor([[2., 1., 4.],
        [3., 5., 4.],
        [1., 2., 0.],
        [4., 3., 2.]])
tensor(1.6667)


In [7]:
#REshape tensor into column vector
b_reshape = b.view(-1,1)
print(b_reshape)
b= b.view(-1,1) # 1 row and 12 columns

tensor([[2],
        [1],
        [4],
        [3],
        [5],
        [4],
        [1],
        [2],
        [0],
        [4],
        [3],
        [2]])


In [10]:
# 3-D tensor( channels, rows, columns)
three_dim = torch.randn(2,3,4)
print(three_dim)

tensor([[[-0.7102,  0.4950,  0.6371, -0.8625],
         [ 0.5603,  0.0982,  0.7867, -0.0406],
         [ 0.1060, -0.3549,  0.2598,  0.8837]],

        [[-0.8305,  0.0265,  0.1740,  0.2773],
         [-0.9103,  0.6071, -0.0610,  0.5561],
         [ 1.3821, -0.2957, -0.1735, -0.6914]]])
